In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('olist_data/olist_customers_dataset.csv')
df1.sample(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
58053,64a86356e147cbebd00bda1953a413b8,99bcd7246cddcb0dd90989f4bcde3ddb,31150,belo horizonte,MG
35741,a12c7d650184df118001b3cebaf3b150,1376c487ee3920f2431e975211dffcb1,6693,itapevi,SP
56528,c3ea664ff88d7468de59ee62516b0c55,80275de537b6a389930536433e8baed3,14802,araraquara,SP
15096,b3ac014589b31526bee88162838b5b77,654ef7d7479c195d6ff3a45408df0b10,2022,sao paulo,SP
58581,37ffb68c39bd78aec200de254446972f,e8ca08f200cf74746cd5e671efcb61f3,85301,laranjeiras do sul,PR
24989,aa1e003c69c80cdf08ae8225270769b3,a49c7d6d1beaa359c40e7fae01b10b89,13490,cordeiropolis,SP
83581,bcee0525f8f15bfac09a6ca1ba1abf80,f5e6b05b74dd87043041dba3d8957113,8180,sao paulo,SP
42087,49658117b256d5f59316507693ffefc5,4a3e51cfe7e01f71e3d175c6d0b911d4,31030,belo horizonte,MG
81125,0971891520d63f966aafcd261c3384b3,34d3304cccd0c8ba2f3266155dc49610,1525,sao paulo,SP
89825,74fbb79efe8970851ed1762f096e2d4d,2c35d207315b638d53e7730724427348,7094,guarulhos,SP

In [3]:
df1.customer_city.value_counts()

sao paulo            15540
rio de janeiro        6882
belo horizonte        2773
brasilia              2131
curitiba              1521
                     ...
bequimao                 1
andarai                  1
vargem grande            1
curvelandia              1
eugenio de castro        1
Name: customer_city, Length: 4119, dtype: int64

<hr />

In [4]:
df2 = pd.read_csv('olist_data/olist_geolocation_dataset.csv')
df2.sample(10)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
136536,5661,-23.608469,-46.729282,sao paulo,SP
265015,11850,-24.281263,-47.445650,miracatu,SP
328544,14075,-21.129228,-47.784931,ribeirao preto,SP
44531,3061,-23.541866,-46.588919,sao paulo,SP
967857,95320,-28.804456,-51.611365,nova prata,RS
185044,7115,-23.459927,-46.531165,guarulhos,SP
547572,30240,-19.924167,-43.916480,belo horizonte,MG
393352,18602,-22.888883,-48.444722,botucatu,SP
864768,83704,-25.574399,-49.400961,araucaria,PR
473456,24210,-22.906390,-43.131598,niteroi,RJ

In [5]:
df2.geolocation_city.value_counts()

sao paulo               135800
rio de janeiro           62151
belo horizonte           27805
são paulo                24918
curitiba                 16593
                         ...
jacuípe                      1
mar vermelho                 1
quebrangulo                  1
poço das trincheiras         1
poxim                        1
Name: geolocation_city, Length: 8011, dtype: int64

<hr />

In [6]:
df3 = pd.read_csv('olist_data/product_category_name_translation.csv')
df3.sample(10)

                product_category_name product_category_name_english
28            fashion_roupa_masculina         fashion_male_clothing
43  construcao_ferramentas_iluminacao     construction_tools_lights
62                    casa_conforto_2                home_comfort_2
48             livros_interesse_geral        books_general_interest
32                        eletronicos                   electronics
27      construcao_ferramentas_jardim      costruction_tools_garden
7               utilidades_domesticas                    housewares
52            sinalizacao_e_seguranca        signaling_and_security
42                        moveis_sala         furniture_living_room
24                       climatizacao              air_conditioning

In [7]:
df3.product_category_name.unique()

array(['beleza_saude', 'informatica_acessorios', 'automotivo',
       'cama_mesa_banho', 'moveis_decoracao', 'esporte_lazer',
       'perfumaria', 'utilidades_domesticas', 'telefonia',
       'relogios_presentes', 'alimentos_bebidas', 'bebes', 'papelaria',
       'tablets_impressao_imagem', 'brinquedos', 'telefonia_fixa',
       'ferramentas_jardim', 'fashion_bolsas_e_acessorios',
       'eletroportateis', 'consoles_games', 'audio', 'fashion_calcados',
       'cool_stuff', 'malas_acessorios', 'climatizacao',
       'construcao_ferramentas_construcao',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'construcao_ferramentas_jardim', 'fashion_roupa_masculina',
       'pet_shop', 'moveis_escritorio', 'market_place', 'eletronicos',
       'eletrodomesticos', 'artigos_de_festas', 'casa_conforto',
       'construcao_ferramentas_ferramentas', 'agro_industria_e_comercio',
       'moveis_colchao_e_estofado', 'livros_tecnicos', 'casa_construcao',
       'instrumentos_musicais', 'moveis_sala',
       'construcao_ferramentas_iluminacao',
       'industria_comercio_e_negocios', 'alimentos', 'artes',
       'moveis_quarto', 'livros_interesse_geral',
       'construcao_ferramentas_seguranca',
       'fashion_underwear_e_moda_praia', 'fashion_esporte',
       'sinalizacao_e_seguranca', 'pcs', 'artigos_de_natal',
       'fashion_roupa_feminina', 'eletrodomesticos_2',
       'livros_importados', 'bebidas', 'cine_foto', 'la_cuisine',
       'musica', 'casa_conforto_2', 'portateis_casa_forno_e_cafe',
       'cds_dvds_musicais', 'dvds_blu_ray', 'flores',
       'artes_e_artesanato', 'fraldas_higiene',
       'fashion_roupa_infanto_juvenil', 'seguros_e_servicos', 'pc_gamer'],
      dtype=object)